version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taskflow-db
    restart: always
    environment:
      POSTGRES_USER: luis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: